In [ ]:
 #features (1 sim, 0 não)
 #pelo longo?
 #perna curta?
 #faz auau?

 porco1 = [0,1,0]
 porco2 = [0,1,1]
 porco3 = [1,1,0]

cachorro1 =[0,1,1]
cachorro2 =[1,0,1]
cachorro3 =[1,1,1]

# 1 => porco, 0 => cachorro
treino_x = [porco1,porco2,porco3,cachorro1,cachorro2,cachorro3] #nomenclatura padrão: x para os dados e y para a classe que eles pertencem
treino_y = [1,1,1,0,0,0] #as vezes são chamadas de label

In [ ]:
from sklearn.svm import LinearSVC # importando um estimados da biblioteca Scikit-learn do python

model = LinearSVC()
model.fit(treino_x, treino_y) #faz com que o modelo se adapte as duas informações dados e classes, como o aprendizado é supervisionado
#precisamos fornecer as classes

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [ ]:
animal_misterioso =[1,1,1]
model.predict([animal_misterioso]) #modelo tentando prever qual classe pertence esse animal misterioso
# o predict espera um array com varios itens, então precisamos passar uma lista com varios itens
#o modelo previu que era um cachorro

array([0])

In [ ]:
misterio1= [1,1,1] #cachoro
misterio2=[1,1,0]#cachoro
misterio3=[0,1,1]#porco

teste_x = [misterio1,misterio2,misterio3]
teste_y =[0,1,1] #o resultado que ja sabia que era para teste_x
 #definindo as classes de misteiro1,misterio2 e misterio3

In [ ]:
previsoes = model.predict(teste_x)
previsoes

array([0, 1, 0])

In [ ]:
previsoes == teste_y #podemos fazer essa comparação direta pois previsoes é um array do numpy e o scikit-learn utiliza ele por baixo dos panos


array([ True,  True, False])

In [ ]:
corretos = (previsoes == teste_y).sum()
corretos #numero de acertos

2

In [ ]:
total = len(teste_x)
taxa_de_acertos = corretos/total
print('Taxa de acertos %.2f ' % (taxa_de_acertos*100))


Taxa de acertos 66.67 


In [ ]:
from sklearn.metrics import accuracy_score #buscando uma função que apresente a taxa de acertos diretamente, sem precisar faz a conta anterior

taxa_de_acerto = accuracy_score(teste_y,previsoes)  #accuracy_score mede a precisao das previsoes do modelo 
#valores verdadeiros primeiro e depois as previsoes
print('Taxa de acertos %.2f ' % (taxa_de_acertos*100))

Taxa de acertos 66.67 
